### PR TITLE
Implementing Postgres

### PR DESCRIPTION
**Pull request by GalaDev**

### CODE REVIEW

**Review by devjce — APPROVED** [review]
This looks great so far Andy! I did see a typo on addTables.js on line 12, make sure you spell cleanliness correctly. That was by far the most common typo I made in FEC was spelling that word right. I still can't spell it right. LOL. Other than that nitpick, it looks great.

**Comment by jasonwiesner** [comment]
@GalaDev In database/addTables.js, you might have meant to put your console.log inside the next .then on line 37 to assure it is successful before the logging. Aside from that it LGTM!

**Comment by GalaDev** [comment]
> This looks great so far Andy! I did see a typo on addTables.js on line 12, make sure you spell cleanliness correctly. That was by far the most common typo I made in FEC was spelling that word right. I still can't spell it right. LOL. Other than that nitpick, it looks great.

Great catch! Thanks! I found the npm package 'Check speller' to help prevent future typos.

**Comment by GalaDev** [comment]
> @GalaDev In database/addTables.js, you might have meant to put your console.log inside the next .then on line 37 to assure it is successful before the logging. Aside from that it LGTM!

Yes, def want it on the next .then block. Great catch! Thanks!

**Pull request merged**
