### PR TITLE
Migrate to AWS

### PR DESCRIPTION
**Pull request by GalaDev**

### CODE REVIEW

**Review by jasonwiesner — APPROVED** [review]
LGTM! Nice use of dotenv. Don't see anything in particular that I would improve upon.

**Review by devjce — APPROVED** [review]
Great work Andy! I have zero to add (I tried to find something, but alas). Learned more about .dotenv myself as I just dove into that a few days ago, so reading your super clean code on that will certainly help mine! Looks like you made good progress on getting Postgres spun up on AWS too.

**Comment by GalaDev** [comment]
> Great work Andy! I have zero to add (I tried to find something, but alas). Learned more about .dotenv myself as I just dove into that a few days ago, so reading your super clean code on that will certainly help mine! Looks like you made good progress on getting Postgres spun up on AWS too.

Awesome! Thanks for looking over everything!

**Comment by GalaDev** [comment]
> LGTM! Nice use of dotenv. Don't see anything in particular that I would improve upon.

Awesome! Appreciate the feedback!

**Pull request merged**
